inoreader_appkey = "xLgWshUl06mKIKhT5N37OCsEISi7Rq_z"
inoreader_appid = "1000000535"
inoreader_token = "TEHndjYACSmaLyGkigIhocJDnhO4DwE3"
inoreader_endpoint = "https://www.inoreader.com/reader/api/0"
telegram_token = "370867755:AAGi_Jc4YqFcUButlhRk8JwqofmLOJrKP-4"
telegram_endpoint = "https://api.telegram.org"
chart_id = "89731"